Add channel message scrape tool
randomairborne/discord-power-utils pull request #1
Opened 2024-04-09 17:41 UTC by Fripe070

2024-04-09 19:19 UTC, randomairborne requested changes

2024-04-09 19:19 UTC, randomairborne commented on DownloadChannelMessages.ps1
> +$OutfilePath = "./Output/ChannelMessages.jsonl"
Why is this jsonl? Does that mean something special?

2024-04-12 21:00 UTC, Fripe070 commented on DownloadChannelMessages.ps1
> +$OutfilePath = "./Output/ChannelMessages.jsonl"
[Json lines](https://jsonlines.org/). It means that we can just append lines instead of having to parse and store an entire list in memory, which'd be infeasible on lower ram devices.

2024-04-13 03:54 UTC, randomairborne commented on DownloadChannelMessages.ps1
> +$OutfilePath = "./Output/ChannelMessages.jsonl"
Yay! thanks!

2024-04-13 03:54 UTC, randomairborne approved these changes

2024-04-13 03:54 UTC, merged